# Generated by Django 4.2.1 on 2023-05-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_delete_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="description",),
        migrations.RemoveField(model_name="blog", name="discount_price",),
    ]
