# Generated by Django 4.2.1 on 2023-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_blog_description_remove_blog_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
